#ifndef SODA_LEXER_HPP
#define SODA_LEXER_HPP

#include <string>

#include "soda/token.hpp"

namespace soda {

// The definition of this function gets generated by Flex at build time.
std::vector<Token> tokenize(const std::string &source);

} // namespace soda

#endif
